NavSDK version actualization
mapbox/mapbox-adas-sdk pull request #9
Opened 2023-12-21 16:33 UTC by 0xDAD

2023-12-21 19:43 UTC, averkhaturau submitted a review, later dismissed

2023-12-22 08:19 UTC, dzinad commented
As discussed internally, let's not merge it with a snapshot version.

2023-12-22 08:20 UTC, dzinad requested changes

2023-12-22 08:20 UTC, dzinad commented on samples/android/adas-sdk-example/app/build.gradle
> +    implementation "com.mapbox.navigation:android:2.18.0-adas-preview-7-SNAPSHOT"
As discussed internally, let's not merge it with a snapshot version.

2025-03-05 08:38 UTC, closed without merging